#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin
    username: root
    password: root
    hikari:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/admin
      username: root
      password: root

      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 50
      auto-commit: true
      pool-name: SystemHikariCP
      max-lifetime: 1800000
      leak-detection-threshold: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true
