server:
  port: 8000

spring:
  profiles:
    active: dev

  jackson:
    time-zone: GMT+8

  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect:
          storage_engine: innodb

  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6366
    password:
    #连接超时时间
    timeout: 5000
